# Generated by Django 4.1.1 on 2022-10-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='はじめまして', max_length=120),
        ),
    ]
