# Generated by Django 4.1 on 2023-05-17 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_lastaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastAccess',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
