# Generated by Django 4.1 on 2023-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_lastaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthOfDay',
            new_name='dateOfBirth',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
