# Generated by Django 4.1 on 2023-05-18 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_birthofday_user_dateofbirth_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='質問', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='tag',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
